AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  car-lambdas

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java17
    Architectures: [x86_64]

Resources:

  CarDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CarData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slotId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: slotId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  UnpaidCarsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UnpaidCars
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: carPlate
          AttributeType: S
      KeySchema:
        - AttributeName: carPlate
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PaymentValidationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: payment-validation-bucket

  FineCandidatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FineCandidates
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slotId
          AttributeType: S
        - AttributeName: carPlate
          AttributeType: S
      KeySchema:
        - AttributeName: slotId
          KeyType: HASH
        - AttributeName: carPlate
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  
  FinesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Fines
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: carPlate
          AttributeType: S
        - AttributeName: validationTimestamp
          AttributeType: S
      KeySchema:
        - AttributeName: carPlate
          KeyType: HASH
        - AttributeName: validationTimestamp
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  FinePreparationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FinePreparationFunction/
      Handler: fineprep.FinePreparationLambda::handleRequest
      Environment:
        Variables:
          PRICE: "20"
          FINES_TABLE: Fines
      Events:
        FineCandidatesStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FineCandidatesTable.StreamArn
            StartingPosition: LATEST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Fines

  StoreCarDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StoreCarDataFunction/
      Handler: store.StoreCarData::handleRequest
      Environment:
        Variables:
          TABLE_NAME: CarData
      Events:
        ScheduledTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: CarData

  PaymentCheckingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PaymentCheckingFunction/
      Handler: payment.PaymentCheckerLambda::handleRequest
      Environment:
        Variables:
          VALIDATION_BUCKET: payment-validation-bucket
          UNPAID_TABLE: UnpaidCars
          COOLDOWN_TIME_SECONDS: 60
          TOLERANCE_TIME_SECONDS: 30
      Events:
        CarDataStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt CarDataTable.StreamArn
            StartingPosition: LATEST
      Policies:
        - S3CrudPolicy:
            BucketName: payment-validation-bucket
        - DynamoDBReadPolicy:
            TableName: CarData
        - DynamoDBCrudPolicy:
            TableName: UnpaidCars

  FineCheckingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FineCheckingFunction/
      Handler: fine.FineCheckingLambda::handleRequest
      Environment:
        Variables:
          FINE_CANDIDATES_TABLE: FineCandidates
      Events:
        UnpaidCarStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt UnpaidCarsTable.StreamArn
            StartingPosition: LATEST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: FineCandidates
        - DynamoDBReadPolicy:
            TableName: UnpaidCars

  FineEmailSenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FineEmailSenderFunction/
      Handler: finesender.FineEmailSenderLambda::handleRequest
      Environment:
        Variables:
          SENDER_EMAIL: dsenders06@gmail.com
      Events:
        FinesStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FinesTable.StreamArn
            StartingPosition: LATEST
      Policies:
        - SESCrudPolicy:
            IdentityName: dsenders06@gmail.com

  FineReportStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FineReportStoreFunction/
      Handler: report.FineReportStoreLambda::handleRequest
      Runtime: java17
      MemorySize: 512
      Timeout: 20
      Environment:
        Variables:
          DB_URL: jdbc:postgresql://db-instance-fine-reports.ckjieemwqkan.us-east-1.rds.amazonaws.com:5432/postgres
          DB_USER: postgres
          DB_PASSWORD: 12345.com
      Events:
        FinesStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt FinesTable.StreamArn
            StartingPosition: LATEST
      VpcConfig:
        SecurityGroupIds:
          - sg-0453cd1c886975dd2  # same SG as your RDS
        SubnetIds:
          - subnet-0c0e3e10ea775bb05
          - subnet-05011bf2436e79976
          - subnet-072a7418f4047074f
          - subnet-0ce5e1ccdc98b26cd
          - subnet-06cd5ce60088ca16c
          - subnet-0e1fbc30584e4cf9b
      Policies:
        - AWSLambdaVPCAccessExecutionRole

